Revert "Use harness as published to NPM (#53)"
This reverts commit 917aa1c0ce70225b1711585f50d9ccc5a67527a1.

The reverted commit caused issues in the Windows/NVDA GitHub Action,
where the following error was reported by `run-tester.ps1`:

    Launching automation-harness host
    D:\a\aria-at-gh-actions-helper\aria-at-gh-actions-helper\node_modules\.bin\aria-at-harness-host:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^

    SyntaxError: missing ) after argument list
        at wrapSafe (node:internal/modules/cjs/loader:1378:20)
        at Module._compile (node:internal/modules/cjs/loader:1428:41)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Module._load (node:internal/modules/cjs/loader:1104:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:173:12)
        at node:internal/main/run_main_module:28:49